version: '3.8'

services:
  # NATS Message Broker
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"

  # MySQL Database
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tomok123
      MYSQL_DATABASE: uniqast
      MYSQL_USER: tomok
      MYSQL_PASSWORD: tomok123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Dependency Setup
  node-api:
    image: node:18-bullseye
    container_name: node-api-setup
    working_dir: /usr/src/app
    env_file:
      - ./node-api/.env
    volumes:
      - ./node-api:/usr/src/app
    command: >
      sh -c "npm install && echo '✅ Node.js dependencies installed' && tail -f /dev/null"

  # Golang Dependency Setup
  go-processing-service:
    image: golang:1.23
    container_name: go-processing-setup
    working_dir: /usr/src/processor
    env_file:
      - ./go-processing-service/.env
    volumes:
      - ./go-processing-service:/usr/src/processor
    command: >
      sh -c "go mod tidy && echo '✅ Golang dependencies installed' && tail -f /dev/null"

volumes:
  mysql_data: