version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tomok123
      MYSQL_DATABASE: uniqast
      MYSQL_USER: tomok
      MYSQL_PASSWORD: tomok123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-api:
    build: ./node-api
    container_name: node-api
    environment:
      NODE_ENV: docker
    env_file:
      - ./node-api/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./Files:/app/files
      - ./node-api/logs:/usr/src/app/logs

  go-processing-service:
    build: ./go-processing-service
    container_name: go-processing-service
    environment:
      GO_ENV: docker
    env_file:
      - ./go-processing-service/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - db
    volumes:
      - ./Files:/app/files
      - ./go-processing-service/logs:/app/logs
